name: Swagruha-Interiors-Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated version

      - name: Setup Node
        uses: actions/setup-node@v4  # Updated version
        with:
          node-version: '18'
          cache: 'npm'  # Cache npm dependencies

      - name: Install dependencies
        run: npm ci  # Use npm ci instead of npm install for CI

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4  # Updated version
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    # Add permissions for GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Updated version
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
